apiVersion: v1
kind: ConfigMap
metadata:
  name: swanctl-ikev2-x509ca
  namespace: swan-ikev2
data:
  m0-0ca-2024.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBQTCB6KADAgECAghrFT7O26tv4DAKBggqhkjOPQQDAjAWMRQwEgYDVQQDEwtt
    MC0wQ0EtMjAyNDAeFw0yNDAxMDEwMDAwMDBaFw0zNTEyMzEyMzU5NTlaMBYxFDAS
    BgNVBAMTC20wLTBDQS0yMDI0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEdACI
    5qAj3IJJDS8aOtfJfcCrOLzBahwYmaNaLJi4x8//22A2mXqqxeZ6VG2jLuhQeGuK
    CfrwIWpK8h+OjaF+HKMgMB4wDwYDVR0TBAgwBgEB/wIBADALBgNVHQ8EBAMCAgQw
    CgYIKoZIzj0EAwIDSAAwRQIgeyABEh/DgVV1bH3mIfUOYWWyWh+D7ZDuxMqXwWgC
    skMCIQCkIgbHSWE6XF+yHAznOyAEcbRkHDm51O4whkYufAbG3Q==
    -----END CERTIFICATE-----
