apiVersion: v1
kind: ConfigMap
metadata:
  name: swanctl-ikev2
  namespace: swan-ikev2
data:
  ikev2.conf: |
    # /etc/strongswan/swanctl/conf.d/ikev2-fenix.conf
    connections {
        pubkey-eaptls {
            version = 2
            pools = pool-ipv4
            local {
                auth = pubkey
                certs = le-ikev2-srv.crt
                id = fenix.ubb.menoscero.com
            }
            remote {
                auth = eap-tls
                eap_id = %any
            }
            children {
                tunnel-ubbnet {
                    local_ts = dynamic, 0.0.0.0/0
                    mode = tunnel
                }
            }
        }
    }
    pools {
        pool-ipv4 {
            addrs = 172.31.155.0/24
            dns = 146.83.195.14, 146.83.195.17, 146.83.196.20
        }
    }
