apiVersion: v1
kind: Secret
metadata:
  name: gurobi-lic
  namespace: gurobi-ts
type: Opaque
stringData:
  gurobi.lic: |
    # /opt/gurobi/gurobi.lic
  fake-grb0.sh: |
    #!/bin/sh
    set -ex
    ip link add grb0 type dummy
    ip link set dev grb0 address 01:23:45:67:ab:cd
    ip link set grb0 up
    ip link show grb0
